# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14.x, 16.x]  # Adjust based on the latest LTS version
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install  # or npm ci if you have package-lock.json
    - name: Debug PROD_ENV_FILE secret
      run: echo "Secret value: ${{ secrets.PROD_ENV_FILE }}"
    - name: Create .env file
      run: |
        echo "PROD_ENV_FILE='${{ secrets.PROD_ENV_FILE }}'" > .env
        echo "Contents of .env file:"
        cat .env
    - name: Display PROD_ENV_FILE
      run: echo "PROD_ENV_FILE=${{ env.PROD_ENV_FILE }}"
    - name: Debug .env file
      run: |
        echo "Current directory: $(pwd)"
        echo "Contents of .env file:"
        ls -la
        cat .env







    
    

  
